#!/usr/bin/env python

import click
import fsksc.server
import os

flaskenv_app_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'fsksc', 'server', 'app.py')
flaskenv_app_func = '{}:create_fsksc_app'.format(flaskenv_app_path)
os.environ['FLASK_APP'] = flaskenv_app_func

@click.group()
def fsksc_cli():
    pass

@fsksc_cli.command()
def cmd1():
    print("Command one")

@fsksc_cli.command()
def cmd2():
    print("Command two")

# Import the flask commands under the nf-core monitor cli group
fsksc_cli.add_command(fsksc.server.app.server)

if __name__ == '__main__':
    fsksc_cli()
