#!/usr/bin/env python

import click
import flask
import fsksc.server
import os

# Set env variable FLASK_APP so that the flask server can run as a click subcommand
flaskenv_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'fsksc', 'server', '.flaskenv')
flask.cli.load_dotenv(flaskenv_path)

@click.group()
def fsksc_cli():
    pass

@fsksc_cli.command()
def cmd1():
    print("Command one")

@fsksc_cli.command()
def cmd2():
    print("Command two")

# Import the flask commands under the nf-core monitor cli group
fsksc_cli.add_command(fsksc.server.app.server)

if __name__ == '__main__':
    fsksc_cli()
